language: python

python: "2.7"

install:
    - cp buildout/* .
    - mkdir -p buildout-cache/eggs
    - mkdir -p buildout-cache/downloads
    - python bootstrap.py -c travis.cfg
    - bin/buildout -N -t 3 -c travis.cfg

script: bin/coverage run bin/test -s seantis.dir.roadworks

after_success:
    - pip install coveralls
    - python -m coverage.pickle2json
    - coveralls

sudo: false
